# Generated by Django 3.1.7 on 2021-04-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tbl_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_enderecos',
            name='cliente',
        ),
        migrations.AddField(
            model_name='tbl_clientes',
            name='deletado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_enderecos',
            name='cliente_id',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_enderecos',
            name='deletado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
