apiVersion: v1
kind: Pod
metadata:
  name: api-produtos
  labels:
    api: produtos
spec:
  containers:
    - name: api-produtos
      image: konkah/desafio_api_produtos:latest
      ports:
        - containerPort: 80
